version: '3.3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    image: python:3.11.2
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 8000:8000
    command: bash -c "cd app
                      && pip install -r requirements.txt
                      && make start-server"